export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_BASKET = 'ADD_BASKET'
export const REMOVE_BASKET = 'REMOVE_BASKET'
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT'
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT'
export const CHANGE_INPUT_PRODUCT = 'CHANGE_INPUT_PRODUCT'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

